### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Goulsan** [epicstudios856/Vectras-windows-emulator#12]
When im starting vm, its show message, and crash.
Vm os: alpine
Android 13
[vectraslog.txt](https://github.com/epicstudios856/Vectras-windows-emulator/files/13903207/vectraslog.txt)

**Comment by epicstudios856** [comment]
Temporary solution:
Down grade memory to 511
Custom memory in preference 

We will fix it thank you

**Comment by epicstudios856** [comment]
Fixed now update to 2.4
https://vectras.netlify.app/download
